name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        erlang:
          - 23.0.4
          - 23.1.5
          - 23.2.7.5
          - 23.3.4.17
          - 24.0.6
          - 24.1.7
          - 24.2.2
          - 24.3.4.5
          - 25.0.4
          - 25.1

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
